import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/components/Sidebar/SIdebar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger>
                  <SidebarTrigger />
                </TooltipTrigger>
                <TooltipContent>
                  <p>CTRL+b to toggle menu</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
            <div
              style={{
                padding: 20,
              }}
            >
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
