"use client";
import { Indent } from "@/app/placement/contracts";
import React, { useEffect, useState } from "react";
import PlacementTable from "./PlacementTable";

const PlacementTemplate = () => {
  const [indents, setIndents] = useState<Indent[]>([]);
  const getActiveDemands = async () => {
    try {
      throw new Error();
    } catch {
      const data = {
        message: "Ok",
        success: true,
        responseTime: 1730897113,
        data: {
          count: 4369,
          size: null,
          page: null,
          defaultFilter: false,
          indents: [
            {
              demandId: 3434456,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Bawal - Lucknow",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730893073,
              vehicleNumber: null,
              consignerFreight: 26471.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: "prashant.s@wheelseye.com",
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "Active",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/0",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 4031,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: true,
              biddingActive: false,
            },
            {
              demandId: 3434454,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Bawal - Lucknow",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730892220,
              vehicleNumber: null,
              consignerFreight: null,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "Not Assigned",
              fareStatus: "ALL",
              followUpDate: null,
              appResponse: "0/0",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: true,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 4892,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: false,
            },
            {
              demandId: 3434453,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730899800,
              creationTime: 1730891061,
              vehicleNumber: null,
              consignerFreight: 22042.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 6027,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: true,
              biddingActive: false,
            },
            {
              demandId: 3434452,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730899800,
              creationTime: 1730890860,
              vehicleNumber: null,
              consignerFreight: 22042.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 6175,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: true,
              biddingActive: false,
            },
            {
              demandId: 3434450,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730896200,
              creationTime: 1730889310,
              vehicleNumber: null,
              consignerFreight: 19261.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 7731,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: false,
            },
            {
              demandId: 3434449,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730889127,
              vehicleNumber: null,
              consignerFreight: 22042.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 7949,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: true,
              biddingActive: false,
            },
            {
              demandId: 3434448,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730896200,
              creationTime: 1730889073,
              vehicleNumber: null,
              consignerFreight: 22042.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 8001,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: true,
              biddingActive: false,
            },
            {
              demandId: 3434447,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730896200,
              creationTime: 1730889025,
              vehicleNumber: null,
              consignerFreight: 19261.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 8059,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: false,
            },
            {
              demandId: 3434446,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730888496,
              vehicleNumber: null,
              consignerFreight: 22042.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 8179,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: true,
              biddingActive: false,
            },
            {
              demandId: 3434445,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730896200,
              creationTime: 1730888430,
              vehicleNumber: null,
              consignerFreight: 21218.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 8654,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: false,
            },
            {
              demandId: 3434444,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730896200,
              creationTime: 1730888329,
              vehicleNumber: null,
              consignerFreight: 22042.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 8716,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: true,
              biddingActive: false,
            },
            {
              demandId: 3434443,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730896200,
              creationTime: 1730887980,
              vehicleNumber: null,
              consignerFreight: 22042.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 9070,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: true,
              biddingActive: false,
            },
            {
              demandId: 3434442,
              consignmentId: null,
              consignerName: "Prashant Sharma Testing",
              consignerBillingName: "Prashant Testing ",
              laneName: "Gurgaon - Shimla",
              vehicle: "Open  | 4 tyre  | 1.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730896200,
              creationTime: 1730887858,
              vehicleNumber: null,
              consignerFreight: 19261.0,
              operatorFreight: null,
              timeToClose: null,
              assignedTo: null,
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: null,
              freightApproved: false,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "DR",
              fareStatus: "CONSIGNER_FREIGHT",
              followUpDate: null,
              appResponse: "0/3",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 9188,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: null,
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: false,
            },
            {
              demandId: 3434440,
              consignmentId: 2035548,
              consignerName: "Raj super fast",
              consignerBillingName: "Raj super fast",
              laneName: "Gurgaon - Jaisalmer",
              vehicle: "Open  | 4 tyre  | 2.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730885819,
              vehicleNumber: "UP84YV3893",
              consignerFreight: 23000.0,
              operatorFreight: 22200.0,
              timeToClose: null,
              assignedTo: "hemanth.kumar@wefreight.co.in",
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: 100.0,
              freightApproved: true,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "Token Paid",
              fareStatus: "BOTH",
              followUpDate: null,
              appResponse: "1/6",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 2155,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: "Unfit Vehicle",
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: false,
            },
            {
              demandId: 3434439,
              consignmentId: 2035547,
              consignerName: "Raj super fast",
              consignerBillingName: "Raj super fast",
              laneName: "Gurgaon - Jaisalmer",
              vehicle: "Open  | 4 tyre  | 2.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730885791,
              vehicleNumber: "UP92MN9966",
              consignerFreight: 23000.0,
              operatorFreight: 19000.0,
              timeToClose: null,
              assignedTo: "hemanth.kumar@wefreight.co.in",
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: 100.0,
              freightApproved: true,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "Active",
              fareStatus: "BOTH",
              followUpDate: null,
              appResponse: "1/6",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 11315,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: "Consigner asked to cancel",
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: true,
            },
            {
              demandId: 3434438,
              consignmentId: 2035546,
              consignerName: "Raj super fast",
              consignerBillingName: "Raj super fast",
              laneName: "Gurgaon - Jaisalmer",
              vehicle: "Open  | 4 tyre  | 2.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730885765,
              vehicleNumber: "UP71DE4873",
              consignerFreight: 23000.0,
              operatorFreight: 19000.0,
              timeToClose: null,
              assignedTo: "hemanth.kumar@wefreight.co.in",
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: 100.0,
              freightApproved: true,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "Active",
              fareStatus: "BOTH",
              followUpDate: null,
              appResponse: "1/6",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 11343,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: "Consigner asked to cancel",
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: true,
            },
            {
              demandId: 3434437,
              consignmentId: 2035545,
              consignerName: "Raj super fast",
              consignerBillingName: "Raj super fast",
              laneName: "Gurgaon - Jaisalmer",
              vehicle: "Open  | 4 tyre  | 2.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730885737,
              vehicleNumber: "UP53EP1854",
              consignerFreight: 23000.0,
              operatorFreight: 19000.0,
              timeToClose: null,
              assignedTo: "hemanth.kumar@wefreight.co.in",
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: 100.0,
              freightApproved: true,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "Active",
              fareStatus: "BOTH",
              followUpDate: null,
              appResponse: "1/6",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 11370,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: "Vehicle Is Not Empty",
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: true,
            },
            {
              demandId: 3434436,
              consignmentId: 2035544,
              consignerName: "Raj super fast",
              consignerBillingName: "Raj super fast",
              laneName: "Gurgaon - Jaisalmer",
              vehicle: "Open  | 4 tyre  | 2.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730885712,
              vehicleNumber: "UP59HT7969",
              consignerFreight: 23000.0,
              operatorFreight: 19000.0,
              timeToClose: null,
              assignedTo: "hemanth.kumar@wefreight.co.in",
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: 100.0,
              freightApproved: true,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "Active",
              fareStatus: "BOTH",
              followUpDate: null,
              appResponse: "1/6",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 11395,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: "NO GPS",
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: true,
            },
            {
              demandId: 3434435,
              consignmentId: 2035543,
              consignerName: "Raj super fast",
              consignerBillingName: "Raj super fast",
              laneName: "Gurgaon - Jaisalmer",
              vehicle: "Open  | 4 tyre  | 2.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730885687,
              vehicleNumber: "UP59HJ9609",
              consignerFreight: 23000.0,
              operatorFreight: 19000.0,
              timeToClose: null,
              assignedTo: "hemanth.kumar@wefreight.co.in",
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: 100.0,
              freightApproved: true,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "Active",
              fareStatus: "BOTH",
              followUpDate: null,
              appResponse: "1/6",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 11421,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: "Alternate Load",
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: true,
            },
            {
              demandId: 3434434,
              consignmentId: 2035542,
              consignerName: "Raj super fast",
              consignerBillingName: "Raj super fast",
              laneName: "Gurgaon - Jaisalmer",
              vehicle: "Open  | 4 tyre  | 2.0 MT  | 14.0 ft  | 6.0 ft ",
              loadingTime: 1730917799,
              creationTime: 1730885660,
              vehicleNumber: "UP71ZD3966",
              consignerFreight: 23000.0,
              operatorFreight: 19000.0,
              timeToClose: null,
              assignedTo: "hemanth.kumar@wefreight.co.in",
              status: "PENDING",
              expiryCategory: null,
              expiryRemark: null,
              advancePct: 100.0,
              freightApproved: true,
              driverNumber: null,
              assignedToNumber: null,
              subStatus: "Active",
              fareStatus: "BOTH",
              followUpDate: null,
              appResponse: "1/6",
              rfq: false,
              estFreight: null,
              triggerBookingFlow: false,
              priceSearchManually: false,
              systemRate: null,
              targetRate: null,
              subStatusTimeDifference: 11447,
              drBookingTimeLeft: null,
              specialRequest: false,
              consignerType: "R",
              ptl: false,
              remarks: "Consigner asked to cancel",
              lowAvailabilityQuote: false,
              highConfidenceQuote: false,
              biddingActive: true,
            },
          ],
        },
      };
      setIndents(data.data.indents);
    }
  };
  useEffect(() => {
    getActiveDemands();
  }, []);
  return <PlacementTable indents={indents} />;
};

export default PlacementTemplate;
